-- Seoyoung Park
-- CSE 414
-- Homework 3

SELECT DISTINCT F1.origin_city AS city
FROM Flights F1, Flights F2
WHERE F1.origin_city = F2.origin_city
AND F1.actual_time < 3*60
GROUP BY F1.origin_city, F1.actual_time
HAVING F1.actual_time = max(F2.actual_time)
ORDER BY F1.origin_city;

/*
"Aberdeen SD"
"Abilene TX"
"Alpena MI"
"Ashland WV"
"Augusta GA"
"Barrow AK"
"Beaumont/Port Arthur TX"
"Bemidji MN"
"Bethel AK"
"Binghamton NY"
"Brainerd MN"
"Bristol/Johnson City/Kingsport TN"
"Butte MT"
"Carlsbad CA"
"Casper WY"
"Cedar City UT"
"Chico CA"
"College Station/Bryan TX"
"Columbia MO"
"Columbus GA"
"Columbus MS"
"Cordova AK"
"Devils Lake ND"
"Dickinson ND"
"Dillingham AK"
"Dothan AL"
"Dubuque IA"
"Duluth MN"
"Durango CO"
"Eau Claire WI"
"Elko NV"
"Erie PA"
"Escanaba MI"
"Fayetteville NC"
"Flagstaff AZ"
"Florence SC"
"Gainesville FL"
"Garden City KS"
"Gillette WY"
"Grand Forks ND"
"Grand Island NE"
"Great Falls MT"
"Green Bay WI"
"Gunnison CO"
"Gustavus AK"
"Hattiesburg/Laurel MS"
"Hays KS"
"Helena MT"
"Hibbing MN"
"Hickory NC"
"Hobbs NM"
"Hyannis MA"
"Idaho Falls ID"
"Inyokern CA"
"Iron Mountain/Kingsfd MI"
"Jamestown ND"
"Joplin MO"
"Kalamazoo MI"
"Ketchikan AK"
"King Salmon AK"
"Kodiak AK"
"La Crosse WI"
"Lansing MI"
"Laramie WY"
"Lawton/Fort Sill OK"
"Lewiston ID"
"Lynchburg VA"
"Macon GA"
"Manhattan/Ft. Riley KS"
"Marquette MI"
"Marthas Vineyard MA"
"Meridian MS"
"Modesto CA"
"Mosinee WI"
"Muskegon MI"
"Naples FL"
"New Bern/Morehead/Beaufort NC"
"New Haven CT"
"Niagara Falls NY"
"North Bend/Coos Bay OR"
"Oxnard/Ventura CA"
"Paducah KY"
"Pellston MI"
"Petersburg AK"
"Pocatello ID"
"Redding CA"
"Roanoke VA"
"Roswell NM"
"San Luis Obispo CA"
"Santa Maria CA"
"Sault Ste. Marie MI"
"Sioux City IA"
"South Bend IN"
"Springfield IL"
"St. George UT"
"Sun Valley/Hailey/Ketchum ID"
"Texarkana AR"
"Tupelo MS"
"Twin Falls ID"
"Valdosta GA"
"Victoria TX"
"Visalia CA"
"Waco TX"
"Waterloo IA"
"West Yellowstone MT"
"Wichita Falls TX"
"Wrangell AK"
"Yakutat AK"
"Yuma AZ"
*/