-- Seoyoung Park
-- CSE 414
-- Homework 3

SELECT X.dest_city AS city
FROM Flights F
       JOIN (SELECT F1.origin_city, F1.dest_city
             FROM Flights F1
             WHERE F1.dest_city != 'Seattle WA'
             AND F1.dest_city
             NOT IN (SELECT F2.dest_city FROM Flights F2
                     WHERE F2.origin_city = 'Seattle WA')
             GROUP BY F1.origin_city, F1.dest_city) X
       ON F.dest_city = X.origin_city
WHERE F.origin_city = 'Seattle WA'
GROUP BY X.dest_city
ORDER BY X.dest_city;

/*
"Aberdeen SD"
"Abilene TX"
"Adak Island AK"
"Aguadilla PR"
"Akron OH"
"Albany GA"
"Albany NY"
"Alexandria LA"
"Allentown/Bethlehem/Easton PA"
"Alpena MI"
"Amarillo TX"
"Appleton WI"
"Arcata/Eureka CA"
"Asheville NC"
"Ashland WV"
"Aspen CO"
"Atlantic City NJ"
"Augusta GA"
"Bakersfield CA"
"Bangor ME"
"Barrow AK"
"Baton Rouge LA"
"Beaumont/Port Arthur TX"
"Bemidji MN"
"Bend/Redmond OR"
"Bethel AK"
"Billings MT"
"Binghamton NY"
"Birmingham AL"
"Bismarck/Mandan ND"
"Bloomington/Normal IL"
"Bozeman MT"
"Brainerd MN"
"Bristol/Johnson City/Kingsport TN"
"Brownsville TX"
"Brunswick GA"
"Buffalo NY"
"Burlington VT"
"Butte MT"
"Carlsbad CA"
"Casper WY"
"Cedar City UT"
"Cedar Rapids/Iowa City IA"
"Champaign/Urbana IL"
"Charleston SC"
"Charleston/Dunbar WV"
"Charlotte Amalie VI"
"Charlottesville VA"
"Chattanooga TN"
"Chico CA"
"Christiansted VI"
"Cody WY"
"College Station/Bryan TX"
"Columbia MO"
"Columbia SC"
"Columbus GA"
"Columbus MS"
"Columbus OH"
"Cordova AK"
"Corpus Christi TX"
"Crescent City CA"
"Dayton OH"
"Daytona Beach FL"
"Deadhorse AK"
"Des Moines IA"
"Dickinson ND"
"Dillingham AK"
"Dothan AL"
"Dubuque IA"
"Duluth MN"
"Durango CO"
"Eagle CO"
"Eau Claire WI"
"El Centro CA"
"El Paso TX"
"Elko NV"
"Elmira/Corning NY"
"Erie PA"
"Escanaba MI"
"Eugene OR"
"Evansville IN"
"Fargo ND"
"Fayetteville AR"
"Fayetteville NC"
"Flagstaff AZ"
"Flint MI"
"Florence SC"
"Fort Myers FL"
"Fort Smith AR"
"Fort Wayne IN"
"Gainesville FL"
"Garden City KS"
"Gillette WY"
"Grand Forks ND"
"Grand Island NE"
"Grand Junction CO"
"Grand Rapids MI"
"Great Falls MT"
"Green Bay WI"
"Greensboro/High Point NC"
"Greer SC"
"Guam TT"
"Gulfport/Biloxi MS"
"Gunnison CO"
"Gustavus AK"
"Hancock/Houghton MI"
"Harlingen/San Benito TX"
"Harrisburg PA"
"Hartford CT"
"Hayden CO"
"Hays KS"
"Helena MT"
"Hibbing MN"
"Hickory NC"
"Hilo HI"
"Hobbs NM"
"Huntsville AL"
"Hyannis MA"
"Idaho Falls ID"
"International Falls MN"
"Inyokern CA"
"Iron Mountain/Kingsfd MI"
"Islip NY"
"Jackson WY"
"Jackson/Vicksburg MS"
"Jacksonville FL"
"Jacksonville/Camp Lejeune NC"
"Jamestown ND"
"Joplin MO"
"Kalamazoo MI"
"Kalispell MT"
"Key West FL"
"Killeen TX"
"King Salmon AK"
"Kinston NC"
"Knoxville TN"
"Kodiak AK"
"Kotzebue AK"
"La Crosse WI"
"Lafayette LA"
"Lake Charles LA"
"Lansing MI"
"Laramie WY"
"Laredo TX"
"Latrobe PA"
"Lawton/Fort Sill OK"
"Lewisburg WV"
"Lewiston ID"
"Lexington KY"
"Lincoln NE"
"Little Rock AR"
"Longview TX"
"Louisville KY"
"Lubbock TX"
"Lynchburg VA"
"Macon GA"
"Madison WI"
"Manchester NH"
"Manhattan/Ft. Riley KS"
"Marquette MI"
"Marthas Vineyard MA"
"Medford OR"
"Melbourne FL"
"Meridian MS"
"Midland/Odessa TX"
"Minot ND"
"Mission/McAllen/Edinburg TX"
"Missoula MT"
"Mobile AL"
"Modesto CA"
"Moline IL"
"Monroe LA"
"Monterey CA"
"Montgomery AL"
"Montrose/Delta CO"
"Mosinee WI"
"Muskegon MI"
"Myrtle Beach SC"
"Nantucket MA"
"Naples FL"
"New Bern/Morehead/Beaufort NC"
"New Haven CT"
"Newburgh/Poughkeepsie NY"
"Newport News/Williamsburg VA"
"Niagara Falls NY"
"Nome AK"
"Norfolk VA"
"North Bend/Coos Bay OR"
"Oxnard/Ventura CA"
"Paducah KY"
"Pago Pago TT"
"Panama City FL"
"Pellston MI"
"Pensacola FL"
"Peoria IL"
"Petersburg AK"
"Plattsburgh NY"
"Pocatello ID"
"Ponce PR"
"Portland ME"
"Providence RI"
"Raleigh/Durham NC"
"Rapid City SD"
"Redding CA"
"Rhinelander WI"
"Richmond VA"
"Roanoke VA"
"Rochester MN"
"Rochester NY"
"Rock Springs WY"
"Roswell NM"
"Saginaw/Bay City/Midland MI"
"San Angelo TX"
"San Juan PR"
"San Luis Obispo CA"
"Santa Fe NM"
"Santa Maria CA"
"Sarasota/Bradenton FL"
"Sault Ste. Marie MI"
"Savannah GA"
"Scranton/Wilkes-Barre PA"
"Shreveport LA"
"Sioux City IA"
"Sioux Falls SD"
"South Bend IN"
"Springfield IL"
"Springfield MO"
"St. George UT"
"State College PA"
"Sun Valley/Hailey/Ketchum ID"
"Syracuse NY"
"Tallahassee FL"
"Texarkana AR"
"Toledo OH"
"Traverse City MI"
"Trenton NJ"
"Tulsa OK"
"Tupelo MS"
"Twin Falls ID"
"Tyler TX"
"Valdosta GA"
"Valparaiso FL"
"Visalia CA"
"Waco TX"
"Waterloo IA"
"West Palm Beach/Palm Beach FL"
"West Yellowstone MT"
"White Plains NY"
"Wichita Falls TX"
"Wichita KS"
"Williston ND"
"Wilmington NC"
"Worcester MA"
"Wrangell AK"
"Yakutat AK"
"Yuma AZ"
 */